### ISSUE TITLE
Vacuum error when loading osm data

### ISSUE THREAD

**Issue by celiamercier** [Ifsttar/Tempus#11]
Hello guys,
I'm trying to use your Tempus project to compute personal itineraries using OSM data. Installation on Windows worked fine, I was able to compute a shortest path on your tempus_test_db database with the sample_road_plugin, and visualized it under QGIS.
However I can't figure out how to successfully use your tempus loader with my OSM data. I downloaded .osm file from here : http://download.geofabrik.de/europe/france.html and fed your osm2shp++ with it. Then I created a new database with the tempus schema (tempus.sql), and try to load my data with your loader like this :

c:\Python27\python.exe load_tempus -s ....\test_data\martinique -t osm -d "host=localhost dbname=martinique_test user=postgres port=5432" -l tempus.log

But it gives me errors :
SRID needed for osm data type. Assuming EPSG:4326.
Error during postload_sql().
Error during import !

Here is the tempus.log file :

======= Executing SQL reset_import_schema.sql
SET
NOTICE:  le schéma « _tempus_import » n'existe pas, poursuite du traitement
DROP SCHEMA
CREATE SCHEMA
NOTICE:  l'extension « postgis » existe déjà, poursuite du traitement
CREATE EXTENSION

======= SHP2PGSQL restriction.dbf
======= Executing SQL tmpnncysn
SET
SET
SET
ATTENTION:  une transaction est déjà en cours
BEGIN
CREATE TABLE
ALTER TABLE
COMMIT
ATTENTION:  aucune transaction en cours

Shapefile type: Arc
Postgis type: LINESTRING[2]

======= SHP2PGSQL highway.shp
======= Executing SQL tmphs1u79
SET
SET
SET
ATTENTION:  une transaction est déjà en cours
BEGIN
CREATE TABLE
ALTER TABLE
##                        addgeometrycolumn                       

 _tempus_import.highway.geom SRID:4326 TYPE:LINESTRING DIMS:2 
(1 ligne)

CREATE INDEX
COMMIT
ATTENTION:  aucune transaction en cours

======= Executing SQL osm.sql
SET
DO
NOTICE:  la séquence « seq_road_node_id » n'existe pas, poursuite du traitement
DROP SEQUENCE
CREATE SEQUENCE
INSERT 0 17137
CREATE INDEX
NOTICE:  l'index « idx_road_node_geom » n'existe pas, poursuite du traitement
DROP INDEX
CREATE INDEX
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
NOTICE:  la séquence « seq_road_section_import » n'existe pas, poursuite du traitement
DROP SEQUENCE
CREATE SEQUENCE
SELECT 10745
CREATE INDEX
CREATE INDEX
INSERT 0 10745
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
CREATE INDEX
NOTICE:  Add road restrictions
DO
ERREUR:  VACUUM ne peut pas être exécuté dans un bloc de transaction

Have you any idea of what could the problem be ?
Thank you very much for your work.

**Comment by mhugo** [comment]
Hi,
I guess you're using the sources from the master branch.
That is due to the last commit that introduces a VACUUM command. But the way SQL scripts are called (in single transaction mode), forbids to call that.
I've disabled the single transaction mode. Could you update and test with the last commit ?

**Comment by celiamercier** [comment]
Thanks you very much, this seems to fix the problem :)
