### ISSUE TITLE
Shortest path, bad result (bad chosen start and end vertices)

### ISSUE THREAD

**Issue by celiamercier** [Ifsttar/Tempus#14]
Hi guys,
I noticed a probem using the sample_road_plugin.
I used the following points on the ile_de_france osm database :
A = (649852.2252142751, 6858778.845797726)
B = (649750.725317172, 6858876.96575924)

Here is the result :
![problem1](https://cloud.githubusercontent.com/assets/5389397/6783470/38ada376-d17a-11e4-8f22-876fb1ebd910.png)
![problem2](https://cloud.githubusercontent.com/assets/5389397/6783473/3b28f182-d17a-11e4-9aad-53bdbb8bb93a.png)

We can notice two problems :
- The A point is not matched with the closest vertice
- The dijkstra clearly missed the shortest path

What do you think of that ?

**Comment by mhugo** [comment]
Are there one way streets ? Or streets forbidden to cars ?
This simple plugin only considers you are using a car.

**Comment by celiamercier** [comment]
I didn't know that sample_road_plugin was only for cars ! That explains why it make a such long itinerary, because of the one way restriction.
Here is a diagram of the spot :

![problem4](https://cloud.githubusercontent.com/assets/5389397/6786147/ae93a0da-d18a-11e4-94ae-6c5184827a16.png)

But this does not explain why the start point is not binded on the closest street (that is not forbidden for cars).
Also how can I modify the plugin to compute the path as a pedestrian ?

**Comment by mhugo** [comment]
Sorry, my bad, the plugin does the opposite, it is pedestrian only and forbids road sections where pedestrians are not allowed.
For the closest point ... that's because the first allowed mode of your request is pedestrian. Then tempus looks for the closest node allowed for the selected mode. Then it should be the case for the "residential" way. Could you list the attributes of this road_section imported by tempus in the database ?
If you want to modify what road sections are allowed / restricted by the plugin, have a look at the WeightCalculator around lin 41 in sample_road_plugin.cc

**Comment by celiamercier** [comment]
But it really seems that the algorithm avoid to take one way roads in the bad direction, why that ?
As regards the road_section attributes, the only tags are highway: residential and a name: Villa Deshayes. Here is the Tempus attributes :
- id : 3692
- road_type : 4
- node_from : 228945
- node_to : 227931
- traffic_rules_ft : 63
- traffic_rules_tf : 63
- length : 142.358148603373
- car_speed_limit : 50
- road_name : Villa Deshayes
- lane : 0
- roundabout : false
- bridge : false
- tunnel : false
- ramp : false
- tollway : false
- geom : ...

Thanks !

EDIT :
I look at the code.

``` cpp
if (graph[e].traffic_rules() & TrafficRuleCar) == 0)
   return std::numeric_limits<double>::infinity();
```

You were right, according to those lines the sample_road_plugin is meant to be used for car itineraries.
I changed to TrafficRulePedestrian and it solve the problem of shortest path, but not the problem of vertex choice :
![pedestrian_view](https://cloud.githubusercontent.com/assets/5389397/6806361/85c8531c-d248-11e4-9eab-601873a4b3cf.png)

Here is another exemple of a bad vertex binding (there is a vertex just on the A point) :
![qgis_view](https://cloud.githubusercontent.com/assets/5389397/6806554/af02d666-d249-11e4-9587-f95c26967918.png)
This is weird because the chosen vertex belong to the same road than the vertex that should have been taken (its a footway road).

**Comment by celiamercier** [comment]
There a mistake in the tempus function tempus.road_node_id_from_coordinates, but i don't really understand why ...
Anyway I replace it by :

``` sql
create or replace function tempus.road_node_id_from_coordinates_prettystreets( float8, float8 ) returns bigint
as '
select id from tempus.road_node
order by geom <-> st_setsrid(st_point($1, $2), 2154) limit 1
'
language sql;
```

I directly look at nodes instead of roads, and it works. But it is not applicable for the tempus.road_node_id_from_coordinates_and_modes function.

**Comment by celiamercier** [comment]
Here is a view that explain the problem and may help to solve it :
![vertex_choice_problem](https://cloud.githubusercontent.com/assets/5389397/6966071/8136f37a-d956-11e4-84e1-1f9eb18cfa7a.png)

The green point is the point for which I want to find the closest vertex. The green street is the first street that should be selected when looking for the closest one from the vertex with this request :

``` sql
select id, node_from, node_to l from tempus.road_section
order by geom <-> st_setsrid(st_point($1, $2), 2154) limit 1
```

But in reality it is considered by this request as the 6th closest road ! Black roads are considered closer than the green one, and the black node is the closest node return by the whole request. There clearly is a problem here, what that the '<->' do exactly ?

**Comment by mhugo** [comment]
Thanks for this. You're right it comes from the <->. It actually takes the centers of the bounding boxes to compute the distance, my mistake.
The right query would be something like : limit to N (say 10) closest points (using <#>) and then order by st_distance (the real distance computation) and take the first.

**Comment by celiamercier** [comment]
I try this and it works : 

``` sql
with rs as (
select node_from, node_to from tempus.road_section
)
select id from rs, tempus.road_node as p
where rs.node_from = p.id or rs.node_to = p.id
order by p.geom <-> st_setsrid(st_point($1, $2), 2154) limit 1
```

**Comment by mhugo** [comment]
Indeed. Thanks !
