### ISSUE TITLE
Bridge not linked

### ISSUE THREAD

**Issue by celiamercier** [Ifsttar/Tempus#17]
Hi,
I noticed that a bridge has not been correctly linked into the graph. I don't know if this is a special case or if there is other examples like this ... Here is the screenshot of "Parc de la Villette" : 
![solve1](https://cloud.githubusercontent.com/assets/5389397/6848652/cfef89d8-d3ce-11e4-8f62-00a028a1a86a.png)
![osm_view](https://cloud.githubusercontent.com/assets/5389397/6848653/d154f7ae-d3ce-11e4-828e-a986d757fb18.png)

The algorithm you see is my own dijkstra that stop to the closest point of the destination when A and B are detected to be in different connected components. This is the case here, thus the bridge on which is the destination B is not linked to the green road you see (a simple pedestrian road).
Have you any idea why ?

Thank you very much !

**Comment by mhugo** [comment]
Hmmm I would vote for a problem during the post processing of OSM data (in osm_processing.sql, loader side). We avoid connecting roads with bridges, but we should only do that when the road is **under** the bridge. I don't know if there is an easy way to distinguish extreme points of a bridge and  if we can always consider that extreme points must be connected

**Comment by celiamercier** [comment]
When I start the tempus server I have many warning like this :
`/root/tempus/Tempus/src/core/pgsql_importer.cc:290 Cannot add a road cycle from 483516 to 483516`
But I don't know what it means ? Could it be related ?

**Comment by mhugo** [comment]
It don't think it is related. The warning during loading relates to topology problems. Tempus expects a graph, not a multigraph. It means it cannot handle loops (here a node that is connected to himself) or multiple edges between two nodes (more than one edge in the same direction)
