### ISSUE TITLE
Bad information road section

### ISSUE THREAD

**Issue by celiamercier** [Ifsttar/Tempus#18]
Hi,
I'm currently facing a weird problem... There is a street in Paris, Boulevard des filles du Calvaire, that does not have the same information in tempus than in osm.

Tag OSM :
- highway = primary
- maxspeed = 50
- busway = lane
- cycle_way = share_busway

Tempus :
- road_type = 2 (primary)
- traffic_rule = 60 (so disabled for pedestrian and cyclist)
- car_speed_limit = 90 (inside a city ??)
- lane = 0
- roundabout = bridge = tunnel = ramp = tollway = false

I found other cases like that (essentially roads that are marked as primary)

EDIT : Another case here :
Tag OSM :
- foot = yes
- highway = cycleway

Tempus :
- road_type = 2
- traffic_rule = 2 : thus the section is forbidden for pedestrian, despite the tag foot=yes !

I think that there is some oversimplification that are made in the loader. Any idea ?
Thanks

**Comment by celiamercier** [comment]
I check out the code in osm.sql and I found the cause of those problems. There are some fundamental tags that you omit which leads to bad information :
- foot=yes/no
- bicycle=yes/no
- maxspeed

As explained here : http://wiki.openstreetmap.org/wiki/Map_Features#Highway, you can have a footway that have the tag bicycle=yes and you can also have a cycleway that have the tag foot=yes. Futhermore there is many roads in Paris that are primary but not limited to 90km/h and allowed to pedestrians (sidewalk, since we are in a city). This information is given by the tag maxspeed that is set to 50km/h for those roads.

There is also some roads with the tag access=private, it could be good to remove them from the graph.

Where do you select the tags to import ?

**Comment by mhugo** [comment]
To be retested with the new version of the OSM loader
