### ISSUE TITLE
Tempus fails to compute route query on QGis interface 

### ISSUE THREAD

**Issue by haitamlaarabi** [Ifsttar/Tempus#2]
Hi all,
I have followed the steps for setting the Tempus environment. However, the routing on QGis interface fails to produce any results from the database sample (tempus_test_db).
I would like to find the sources of this failure, where are supposed to be the logs ?

**Comment by mhugo** [comment]
Hi.
The WPS server should return an error (the qgis plugin will display it). Or, in a worse scenario, it should crash (and you may have found a bug)
Could you provide more details on your setup: how do you start the server, version of qgis used, what kind of query, etc. ?

**Comment by haitamlaarabi** [comment]
@mhugo 
I installed "tempus-1.2.0-win32-vc9.exe".  At first, I built with VC2013 and used latest versions of QGis and postgres etc. and I got the same problem.
Here is the wps_service in (C:\Program Files (x86)\tempus-1.2.0) output, on dropbox.
https://www.dropbox.com/sh/99jd1i715pd167c/AAB_ILHBitvBBaboGFMssYTAa

It doesn't seem to show any relevant information.
For the versions I use the one provided with "tempus-1.2.0-win32-vc9.exe", and I tried route computing query by providing the start and end nodes.
So what do you think ?

**Comment by mhugo** [comment]
Your server seems to work properly. I notice you are using the wps Windows service. It is still shipped with Tempus, but not very well tested to be honest.
Could you try to stop the service and launch the wps server "by hand" using either the "Local server" configuration tab in the QGIS plugin or using the command line ?
How QGIS behaves when you enter your itinerary request ? Does it freeze ? Do you have some "roadmap" layers created ?

**Comment by haitamlaarabi** [comment]
Done, here are the screenshots:
![tempus1](https://cloud.githubusercontent.com/assets/10712736/6017432/d8548df8-ab8d-11e4-965c-ade60bae7ab8.PNG)
![tempus2](https://cloud.githubusercontent.com/assets/10712736/6017434/dca466da-ab8d-11e4-90f3-a816eea31851.PNG)
![tempus3](https://cloud.githubusercontent.com/assets/10712736/6017435/e10d3864-ab8d-11e4-9cb8-397d944c728a.PNG)
![tempus4](https://cloud.githubusercontent.com/assets/10712736/6017438/e5f4e9f8-ab8d-11e4-839c-b155d9242520.PNG)
![tempus5](https://cloud.githubusercontent.com/assets/10712736/6017441/e8ae7650-ab8d-11e4-8979-437fb02e217d.PNG)

**Comment by mhugo** [comment]
Thanks. I should have looked at the coordinates first. You are outside the extent of the test data (in EPSG 2154). So, the origin and destination points will be the same arbitrary point

**Comment by haitamlaarabi** [comment]
Though, I have tried various points on the network map, but in vain. So is there an ambiguity somewhere in the Data ? How can I verify and fix it ?

**Comment by mhugo** [comment]
No that I know ...
Could you try with "353551.266054, 6688503.433867" as origin and "355054.415145, 6689436.270509" as destination ? This should work

**Comment by haitamlaarabi** [comment]
Done, It worked, but no path is shown on the map.
I have this feeling that, the actual map Data shown on QGis is different from the Data used by tempus plugins for routing (or projection inconsistency).
![tempus3](https://cloud.githubusercontent.com/assets/10712736/6019039/571ee652-ab9c-11e4-8732-c69a92c7655c.PNG)

**Comment by mhugo** [comment]
You then should have a "Tempus_Roadmap_1" layer. Right-click on it and select "Zoom to layer". You should see the roadmap.
What projection are you using ? Try to turn off any On-The-Fly projection.

**Comment by haitamlaarabi** [comment]
Worked finally. So I had to turn-off the on-the-fly projection.
Thanks a lot for your time.
(I might come to you later, since I'm willing to test my own routing algorithm)
![tempus4](https://cloud.githubusercontent.com/assets/10712736/6019431/ad59544a-aba0-11e4-8fe0-b46c563a5a8f.PNG)

Have a nice day

**Comment by mhugo** [comment]
You're welcome. I've added two tickets to improve the user feedback after this discussion #3 #4
I will be happy to help you write a new routing algorithm
