### ISSUE TITLE
missing some deps to the installation documentation

### ISSUE THREAD

**Issue by garaud** [Ifsttar/Tempus#49]
Hi,
I tried to compile the tempus c++ library and CMake did not found the protobuf library. I think it's necessary to compile `osm2tempus`. Update the installation documentation.

Thanks,
Damien

**Comment by autra** [comment]
I confirm that. Please note that protobuf is a dep of `libosmpbf` (referencing #51 here). I guess we still want to depend on it explicitly if we use it directly.
