### ISSUE TITLE
Install the PostgreSQL extension pgtempus with CMake / Makefile

### ISSUE THREAD

**Issue by garaud** [Ifsttar/Tempus#54]
Hi,
It would be nice if the pgtempus extension was installed with a `make install`.
There can be some difficulties:
* sometimes, there are multiples versions of running postgresql (e.g. 9.5, 9.6, etc.)
* maybe the extension dir for postgresql can change depending on the system (RHEL, Debian, etc.)

I think there is the tool `pg_config` which can help. See also the merely Makefile for this extension https://github.com/pramsey/pgsql-ogr-fdw/blob/master/Makefile

Damien

**Comment by mhugo** [comment]
Linked to #47 to automate PostgreSQL detection

**Comment by mhugo** [comment]
Fixed in b17f38c9563
