### ISSUE TITLE
Do we need protobuf-compiler to build tempus?

### ISSUE THREAD

**Issue by autra** [Ifsttar/Tempus#57]
On Ubuntu 16.04, without `protobuf-compiler` installed, I get the following error when building (`cmake -DCMAKE_BUILD_TYPE=Debug ../ &&  make -j4`)

```
[ 67%] Built target astar_road_plugin
make[2]: *** No rule to make target '../src/loader/osm2tempus/PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND', needed by 'src/loader/osm2tempus/fileformat.pb.cc'.  Stop.
CMakeFiles/Makefile2:729: recipe for target 'src/loader/osm2tempus/CMakeFiles/osm2tempus.dir/all' failed
make[1]: *** [src/loader/osm2tempus/CMakeFiles/osm2tempus.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

With `protobuf-compiler` package installed, everything's ok. Do we need to add this dependencie? Am I doing something wrong?

**Comment by mhugo** [comment]
That should have been fixed. Now fileformat.pb.cc (resulting from protoc on fileformat.proto) is shipped with tempus

**Comment by mhugo** [comment]
Oups, I'm wrong ... protoc is needed

**Comment by garaud** [comment]
Can we close this issue so?
