### ISSUE TITLE
load_tempus fails

### ISSUE THREAD

**Issue by haitamlaarabi** [Ifsttar/Tempus#8]
Hi,
Knowing that tempus & Qgis tempus plugins are working fine. When I try to test the load_tempus following "Bordeaux" example. I get this : 

> htm@ubuntu:~/tempus-1.2.0/bordeaux$ ~/$TEMPUS/src/loader/load_tempus -t osm -s ./tempus_shp -S 4326 -d "host=127.0.0.1 user=postgres dbname=tempus_test_db" -R
> Traceback (most recent call last):
>   File "/home/htm/tempus-1.2.0/src/loader/load_tempus", line 7, in <module>
>     import tempus
>   File "/home/htm/tempus-1.2.0/src/loader/tempus/**init**.py", line 22, in <module>
>     from tomtom import MultinetImporter
>   File "/home/htm/tempus-1.2.0/src/loader/tempus/tomtom.py", line 27, in <module>
>     from importer import ShpImporter
>   File "/home/htm/tempus-1.2.0/src/loader/tempus/importer.py", line 28, in <module>
>     from tools import ShpLoader
>   File "/home/htm/tempus-1.2.0/src/loader/tempus/tools.py", line 29, in <module>
>     from dbtools import PsqlLoader
>   File "/home/htm/tempus-1.2.0/src/loader/tempus/dbtools.py", line 28, in <module>
>     from config import *
>   File "/home/htm/tempus-1.2.0/src/loader/tempus/config.py", line 64, in <module>
>     raise OSError("Could not find psql and shp2pgsql.")
> OSError: Could not find psql and shp2pgsql.

Postgis is installed and operational, otherwise tempus wouldn't worked at all. So psql and sh2pgsql are in the Path.

**Comment by mhugo** [comment]
"Postgis is installed and operational, otherwise tempus wouldn't worked at all. So psql and sh2pgsql are in the Path."

Not necessarily. The tempus core makes a raw connection to the postgres server (no need for psql). The QGIS plugin uses the WPS connection.
The loader is looking for psql and shp2pgsql in the PATH environment variable. You could add /usr/lib/postgresql/9.4/bin and lib in the PATH. You can also set variables in config.py

**Comment by haitamlaarabi** [comment]
Thanks, I should have noticed that.

**Comment by haitamlaarabi** [comment]
@mhugo 
But it still get blocked when executing  "osm_processing.sql". After a long moment I interrupt the process.
(command)
~/$TEMPUS/src/loader/load_tempus -t osm -s ./tempus_shp -S 4326 -d "host=127.0.0.1 user=postgres dbname=tempus_bordeaux_db" -R

> ...
> ======= Executing SQL osm_processing.sql
> SET
> NOTICE:  Splitting road sections, please wait ...
> NOTICE:  table "crossing_sections" does not exist, skipping
> CONTEXT:  SQL statement "drop table if exists _tempus_import.crossing_sections"
> PL/pgSQL function inline_code_block line 10 at SQL statement [<========== BLOCKED HERE]
> ^CTraceback (most recent call last):
>   File "/home/htm/tempus-1.2.0/src/loader/load_tempus", line 114, in <module>
>     r = import_osm(args, shape_options)
>   File "/home/htm/tempus-1.2.0/src/loader/load_tempus", line 38, in import_osm
>     return osmi.load()
>   File "/home/htm/tempus-1.2.0/src/loader/tempus/importer.py", line 70, in load
>     ret = self.postload_sql()
>   File "/home/htm/tempus-1.2.0/src/loader/tempus/importer.py", line 83, in postload_sql
>     return self.load_sqlfiles(self.POSTLOADSQL)
>   File "/home/htm/tempus-1.2.0/src/loader/tempus/importer.py", line 105, in load_sqlfiles
>     ret = self.ploader.load()
>   File "/home/htm/tempus-1.2.0/src/loader/tempus/dbtools.py", line 111, in load
>     p.communicate( self.sqlfile )
>   File "/usr/lib/python2.7/subprocess.py", line 796, in communicate
>     self.wait()
>   File "/usr/lib/python2.7/subprocess.py", line 1376, in wait
>     pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
>   File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
>     return func(*args)
> Cancel request sent
> KeyboardInterrupt
> htm@hubuntu:~/tempus-1.2.0/bordeaux$ ERROR:  canceling statement due to user request
> CONTEXT:  SQL statement "create table _tempus_import.crossing_sections as
> select id1, id2, geom from
> (
>   select
>     rs1.id as id1, rs2.id as id2, st_geometryn(st_multi(st_intersection(rs1.geom, rs2.geom)),1) as geom,
>     -- compute the intersection number
>     rank() over (partition by rs1.id order by rs2.id) as num_inter1,
>     rank() over (partition by rs2.id order by rs1.id) as num_inter2
>   from
>     tempus.road_section as rs1,
>     tempus.road_section as rs2
>   where
>     st_intersects(rs1.geom, rs2.geom) and
>     rs1.id <> rs2.id and
>     rs1.node_from <> rs2.node_to and
>     rs1.node_from <> rs2.node_from and
>     rs1.node_to <> rs2.node_from and
>     rs1.node_to <> rs2.node_to
>   and
>     -- do not include linestring intersections
>     geometrytype(st_multi(st_intersection(rs1.geom, rs2.geom))) = 'MULTIPOINT'
>   and
>     -- do not cut bridges and tunnels
>     not rs1.tunnel and not rs2.tunnel and not rs1.bridge and not rs2.bridge
> ) t
> -- only select the first intersection (more stable than distinct)
> where
>   num_inter1 = 1
> and
>   num_inter2 = 1
> and
>   id1 < id2"
> PL/pgSQL function inline_code_block line 11 at SQL statement

Maybe this due to the previous command:
(command)
osmosis --read-pbf ./aquitaine-latest.osm.pbf --bb left=-0.8749 top=45.269 right=0.0505 bottom=44.3508 --wx - | osm2shp++ -d ./tempus_shp /dev/stdin

which produces somethings like

> ...
> way #323478265 references undefined node #2142841353
> way #323478265 references undefined node #2142841391
> way #323478265 references undefined node #2142841438
> ...
> Untyped restriction #3688006
> Feb 06, 2015 4:12:13 AM org.openstreetmap.osmosis.core.Osmosis run
> INFO: Pipeline complete.
> Feb 06, 2015 4:12:13 AM org.openstreetmap.osmosis.core.Osmosis run
> INFO: Total execution time: 138924 milliseconds.

**Comment by mhugo** [comment]
It's not blocking ... it is just slow. That's the part where ways imported from the shapefile must be split. I know there is still room for improvements here. You should see one of youre core at 100% during this "blocking". On my machine, it takes about 10 minutes to process and import the Bordeaux data

**Comment by haitamlaarabi** [comment]
Actually, it was like 1h30 or more (time to have dinner and get back). I have a Dell, i5 with 8Go RAM.

**Comment by mhugo** [comment]
Indeed, that is too long. Something is going wrong here. I've just tested with the current geofabrik dump, and it works for me.

By the way you should use osmosis >= 0.42. Prior versions (including the one on ubuntu repo) does not handle large IDs (64bits) and will result in undefined nodes. But that does not explain your error.

Things to test:
- does your generated shapefile seem ok when opened with qgis ?
- try on a smaller subset

**Comment by haitamlaarabi** [comment]
Okay. So the previous osmosis (apt-get install osmosis) was producing something like this, I noticed it from the postgis import. I deleted it, and cloned (https://github.com/openstreetmap/osmosis.git) then build it, and when I loaded the highway.shp into QGis, it produced the same piece of art.
So, the problem is elsewhere. Could it be "osm2shp++" ? 
The command I'm using

> ~/osmosis/package/bin/osmosis --read-pbf ./aquitaine-latest.osm.pbf --bb left=-0.8749 top=45.269 right=0.0505 bottom=44.3508 --wx - | osm2shp++ -d ./tempus_shp /dev/stdin

![osmosis](https://cloud.githubusercontent.com/assets/10712736/6078723/3089888c-adfc-11e4-9183-5dc2b16edb38.PNG)

Regarding this one, it was downloaded as osm file from QGis, then run osm2shp++ to generate shape files.
![osmosis2](https://cloud.githubusercontent.com/assets/10712736/6082712/b29cb6e2-ae23-11e4-963a-e9cc701d5557.PNG)

**Comment by mhugo** [comment]
Wow ... could you share your .pbf file so I can try to reproduce ?

**Comment by haitamlaarabi** [comment]
here is the link for pbf
https://mega.co.nz/#!NF0nkbqL!YC2HmDcjvEWt11Bfi6uVtSjyV2jVuPk0ySMz4cHP61E

**Comment by mhugo** [comment]
Thanks. Unfortunately, I cannot reproduce ... the conversion works nicely here ... 

Can you retry with a smaller extent, like 
--bb left=-0.06 top=45.0 right=0.05 bottom=44.8

And also share the raw XML file you have from osmosis ?

**Comment by haitamlaarabi** [comment]
the problem persist:
![capture](https://cloud.githubusercontent.com/assets/10712736/6105803/8c9ef2ae-b05b-11e4-868f-5f6ac50244a1.PNG)

Here is the  dumb.osm
https://mega.co.nz/#!1Ac3kZaZ!QKGOsnQ4Xivl0Kr6nkOaT8ErL_iHjU6wuvk_RfDYadM

**Comment by mhugo** [comment]
Thanks. Again, it works well for me.
I guess your osm2shp++ comes from the master branch of the sources ?
On what system are you running it ? (32bits or 64bits) ?
Could you share the obtained .shp ?

**Comment by haitamlaarabi** [comment]
Yes, I was suspicious toward osm2shp++.
I cloned the master branch on ubuntu (32 bits), installed in a virtual machine. (the host machine is 64bits)

**Comment by haitamlaarabi** [comment]
Hi @mhugo,
have you reproduced the same anomaly ?

**Comment by mhugo** [comment]
Sorry. No I can't reproduce. I suspect a 32 bits issue. I've updated a bit the osm2shp code on the master.
Could you retry with the new code ? I will try to test it on a 32bit platform in the mean time.

**Comment by haitamlaarabi** [comment]
What have you done ?
Working like charm. Good job.

**Comment by mhugo** [comment]
Ah nice !
We've stupidly used "int" C type for integers in osm2shp. Which are 32bits long on 32bits machines ... not enough to store osm large 64 bits identifiers. This works on 64bits platforms, because the int type is 64bits long in this case.
